### ISSUE TITLE
Can I afferent in a binary image?

### ISSUE THREAD

**Issue by iori2882** [zapolnoch/node-tesseract-ocr#10]
await tesseract.recognize("image.jpg")
I want to pass in a binary image directly at image.jpg?Thank you for your answer!!!

**Comment by zapolnoch** [comment]
Unfortunately, you can't pass a binary image. We have a [issue](https://github.com/zapolnoch/node-tesseract-ocr/issues/1) about that.
But you can save the binary data as a file in a [temporary folder](https://nodejs.org/api/os.html#os_os_tmpdir) and use the path to that file.

**Comment by iori2882** [comment]
Thank you for your answer!!!
