### ISSUE TITLE
his tesseract has no URL support

### ISSUE THREAD

**Issue by petekblaz** [zapolnoch/node-tesseract-ocr#19]
Is there anything I can do to add URL support to this package? I keep getting error:
`Command failed: tesseract "https://tesseract.projectnaptha.com/img/eng_bw.png" stdout -l eng --oem 1 --psm 3
Error, this tesseract has no URL support
Error during processing.`

tesseract version I have is: 5.0.0-alpha-20201231-171-g04173

**Comment by NOVA52** [comment]
same

**Comment by zapolnoch** [comment]
v2.2.0 fixed
