### ISSUE TITLE
Can't get 'digits' preset to work

### ISSUE THREAD

**Issue by abcd-ca** [zapolnoch/node-tesseract-ocr#3]
This is my source:

```
const tesseract = require('node-tesseract-ocr')


const config = {
  lang: 'eng',
  oem: 1,
  psm: 6,
  // tessedit_char_whitelist: '0123456789',
  presets: ['digits']
}

tesseract
  .recognize('./image4.png', config)
  .then(text => {
    console.log('Result:', text)
  })
  .catch(err => {
    console.log('error:', err)
  })
```

This is the image: 
![image4](https://user-images.githubusercontent.com/1296103/48918709-4608c700-ee43-11e8-90f6-0caad48e944f.png)

The output I'm getting is, "Result: x 4606   : -4809 Z: 698".

Expected output: "Result: 4606-4809698". (I don't know if it should be delimited or not but there shouldn't be any letters.  I have tried a number of things:

Using the whitelist in config directly,
```
const config = {
  lang: 'eng',
  oem: 1,
  psm: 6,
  tessedit_char_whitelist: '0123456789'
}
```

I've also tried without a digits file and with. With a digits file, the filename is just 'digits' with no extension and I've tried putting it in the same location as my app.js (same dir where I run the script above) and I've also tried putting the digits file here: './tessdata/configs/digits'. 

My digits file contains,
```
tessedit_char_whitelist 0123456789
```

What am I doing wrong?

**Comment by zapolnoch** [comment]
Whitelisting is not implemented for the new LSTM based language models (--oem 1). See [#751](https://github.com/tesseract-ocr/tesseract/issues/751).
Try ``oem: 0`` or another [possible workarounds](https://github.com/tesseract-ocr/tesseract/issues/751#issuecomment-423521780).
